### ISSUE TITLE
[not-an-issue] What are you building?

### ISSUE THREAD

**Issue by obscuren** [toysrtommy/terminal-dapp-ide#1]
Your screenshots got me very, very curious as to what you are building. I can see you're using the `develop` branch of [go-ethereum](https://github.com/ethereum/go-ethereum) and you're using the new native `accounts/abi` bindings. 

Any chance you can shed some light on this? :-)

**Comment by toysrtommy** [comment]
Jeff, good observations :) I'm a co-founder at String (
http://string.technology). We're building Autonomous Finance DAO that is
essentially a parallel financial system on Ethereum - essentially making
engineers the new bankers. Some slides here:
http://www.slideshare.net/tomding/autonomous-finance-stanford
